### ISSUE TITLE
laplace: default prediction settings

### ISSUE THREAD

**Issue by elcorto** [lightning-uq-box/lightning-uq-box#129]
[This is a re-post of a question I had in a Helmholtz-internal UQ channel, where Nina Maria Gottschling made us aware of this package.] 
                                                                                                                                                                                      
In [the docs](https://lightning-uq-box.readthedocs.io/en/latest/tutorials/regression/laplace.html) you mention that *Given posterior distribution during inference on unseen data, we cannot compute the full posterior predictive distribution but instead resort to sampling ... to approximate the predictions*. I guess that would be true for something like

```py
# Laplace from MAP model
la = Laplace(model, likelihood="regression")
la.fit(train_loader)

# ... optimize prior precision and sigma using empirical Bayes, skipped ...

# predict
samples_mean, samples_var = la(X_test, pred_type='nn', link_approx="mc")
```

However, the default setting when calling a fitted `Laplace` instance is, as I understand, the one from https://arxiv.org/abs/2008.08400 where

```py
mu, cov = la(X_test, pred_type='glm', link_approx="probit")
```

where `mu` is the prediction of shape `(N, dim_out)` if `X_test.shape = (N, dim_in)` and `cov` is the full covariance of shape `(N, dim_out, dim_out)`, so one cov matrix `cov[i,...]` of shape `(dim_out, dim_out)` per point `X_test[i,...]`. Since I can't see `pred_type='nn', link_approx="mc"` in the code, I wonder whether you really use sampling.

**Comment by nilsleh** [comment]
Hi @elcorto, thanks for your comment. You are definitely correct, we are not being precise here. In the docs we are mainly trying to give an intuition of how the method works as "originally" proposed, and we did not go into all the details of different prediction schemes with the Laplace Approximation. Hence, as you point out correctly, we are not actually sampling. 

Would you be willing to open a PR to improve the docs statement? And additionally, I suppose it would be worthwhile to add arguments that give the user control over the prediction type. That could be included in the PR as well. If not I am happy to do it and get your feedback if possible.

**Comment by elcorto** [comment]
Thank you for trusting my ability to improve the package docs and code :) However, I tend to not send PRs over to packages which I do not use in production. I am however more than happy to review a PR and help to improve it that way.

In terms of API, one could add keywords to `predict_step()` which would be passed to `forward()` where users can specify `pred_type=..., link_approx=...`, so kwds which are passed down to `laplace.baselaplace.ParametricLaplace.__call__()`. I'm not sure if `predict_step()` is the correct user-facing place to put this, since I don't use Lightning myself, which is also why I'm hesitant to send a PR. Another thing to consider is that the output is different (covariance when using `pred_type="glm"` or samples when `pred_type="nn", link_approx="mc"`). One can of course generate samples given a `mu` and `cov` and one can estimate a `cov` given just samples, I just don't know if `lightning-uq-box` can handle that transparently or if some refactoring is needed to support that.

In terms of docs, I'd basically add that the default prediction setting is the `laplace` package's default (as stated above) which is the one from https://arxiv.org/abs/2008.08400 (wouldn't hurt to double-check that) and which you already document [here](https://lightning-uq-box.readthedocs.io/en/latest/tutorials/regression/laplace.html#Additional-Resources). If users have the ability to select `pred_type`, then the sampling part of the docs can also be kept, but updated by the Laplace kwds needed to switch that on.

Side note: Please do not read my comments as critique of the work that went into this package -- I very much appreciate the effort to provide people with access to such a wide range of UQ methods behind a, as much as possible and reasonable, unified API. I am doing similar work in a different project (focus is "just" on Laplace and deep ensembles) and I am therefore aware of the challenges. This package is a valuable resource, even if I don't use it in production (yet). Also I appreciate the fact that you implement and clearly distinguish between "Deep Ensembles" (what we came to term  "simple ensembles", since the method is general ensembling independent of the fact that the model is a NN) and "Deep Ensembles GMM" as described in [the deep ensemble paper](https://arxiv.org/abs/1612.01474).
