### ISSUE TITLE
laplace: hyper-parameter optimization: is `sigma_noise` optimized?

### ISSUE THREAD

**Issue by elcorto** [lightning-uq-box/lightning-uq-box#130]
[This is a re-post of a question I had in a Helmholtz-internal UQ channel, where Nina Maria Gottschling made us aware of this package.]

In the [laplace package's regression example](https://github.com/aleximmer/Laplace/blob/main/examples/regression_example.py#L36-L44) the prior's variance and the likelihood's homoscedastic noise is optimized by empirical Bayes (maximization of the marginal likelihood, as one would also do in a Gaussian Process, say). Here, this is implemented in `lightning_uq_box.uq_methods.laplace_model.tune_prior_precision()`. However, in `LaplaceBase.on_test_start()` the Laplace package's `self.laplace_model.optimize_prior_precision(method="marglik")` is used, which "only" optimizes the prior variance. In `predict_step()` the code accesses `self.laplace_model.sigma_noise` but since this doesn't seem to be optimized, I'm not sure I understand where the value comes from (esp. if it is the default `Laplace(..., sigma_noise=1)`.

**Comment by nilsleh** [comment]
@elcorto Thanks for your relevant question. I actually ran into similar questions with our last project and made an [issue](https://github.com/aleximmer/Laplace/issues/142) on the laplace package, where I also followed their docs. Happy to discuss how we can improve the docs or the implementation to further support this, but thought that I would give you time to read that issue first.

**Comment by nilsleh** [comment]
Closing this with the merge. Thanks again for the very valuable feedback and improvements :)
