### ISSUE TITLE
`DeepEnsembleRegression` doesn't reduce to `MVERegression` for 1 member

### ISSUE THREAD

**Issue by elcorto** [lightning-uq-box/lightning-uq-box#143]
When building a MVE-GMM ensemble with one `MVERegression` member, then the GMM equations for mean and variance should reduce to the case of a single `MVERegression` model. This is not the case for the sigmas (`pred_uct`) of `DeepEnsembleRegression`.

The reason is that in `compute_aleatoric_uncertainty()` and `compute_predictive_uncertainty()` in `lightning_uq_box/eval_utils/uq_computation.py`, `sample_sigma_preds` needs to be squared, in line with Kendal 2017 (https://arxiv.org/abs/1703.04977) eq. 9, which these functions reference.

I can send a PR with a fix (just 2 lines) and with a test that catches the error (regression case), but I'm not sure what else this might affect -- I had trouble installing the stack for running all tests (in particular hydra), so I couldn't run the test suite. My test doesn't use hydra and shows that the fix works. Please let me know. We have applied this fix internally for our use case, but It would be nice to see it upstream as well I guess.

**Comment by nilsleh** [comment]
Hi @elcorto . I hadn't considered the case, because I assumed that if you just have one member then I assumed one would use the member class itself, so `MVERegression` in that case. Maybe, this should be made clear, or also be handled like you suggest. Or maybe I am overlooking what the use case is for the ensemble class with just one member? 

Apologies for the trouble with the tests. I intended that doing `pip install lightning-uq-box[dev]` would install all dependencies including the ones required to do tests, but sounds like there is an error. Could you send me the error so I can investigate?

**Comment by elcorto** [comment]
Regarding the MVE part: yes you are correct, one `MVERegression` wrapped in `DeepEnsembleRegression` doesn't make sense. I used it as a test to find out why I wasn't getting calibrated results with `DeepEnsembleRegression`, since using that with a single `MVERegression` member must produce the same results (up to numerical precision) as a standalone `MVERegression`. The reason was the missing squared sigma as described above. I can open a PR which includes the fix and a test. Since the fix is trivial, you may also implement that and a test yourself. Please let me know.

Regarding test tooling: this was a mistake on my end. Tests work now. I only found a couple of tests failing when using a GPU machine. On CPU all pass, but I will open a separate issue for that.

**Comment by elcorto** [comment]
Ah, the only thing I had to install to make tests work was `jsonargparse[signatures]>=4.27.7`. However, I installed the test deps by hand and skipped the docs libraries listed in the `dev` section, so `jsonargparse` might be a dep of one of them.  I suggest to maybe separate test and docs deps in `pyproject.toml`.

**Comment by nilsleh** [comment]
> I can open a PR which includes the fix and a test. Since the fix is trivial, you may also implement that and a test yourself. Please let me know.

Yes, that be great if you can make a PR if have the fix already!

**Comment by nilsleh** [comment]
> Ah, the only thing I had to install to make tests work was `jsonargparse[signatures]>=4.27.7`. However, I installed the test deps by hand and skipped the docs libraries listed in the `dev` section, so `jsonargparse` might be a dep of one of them. I suggest to maybe separate test and docs deps in `pyproject.toml`.

Ah you are correct, `jsonargparse[signatures]` is listed as a dependency for the CI requirements but not in `pyproject.toml` for the `dev` section. Will separate them. Thanks for pointing that out!
