### ISSUE TITLE
Possibly redundant parameters in DeepEnsemble classes

### ISSUE THREAD

**Issue by codingS3b** [lightning-uq-box/lightning-uq-box#149]
I noticed that all models inheriting from `DeepEnsemble` require the parameters `n_ensemble_members` and `ensemble_members` where the second is supposed to be a list of length equal to the first.
So maybe it is sufficient to only pass the `ensemble_members` list and obtain the number of members from the length of this list?

I might be overseeing something here, so this is more a question/suggestion.

**Comment by nilsleh** [comment]
@codingS3b Good point, thanks. At some point I felt like it was necessary, but I cannot remember and looking at the code now it seems indeed redundant. Do you want to open a PR to fix that? Otherwise I can also do it :)

**Comment by codingS3b** [comment]
Sure, I can do it...I'm just not sure if it is enough to make changes in the `deep_ensemble.py` module or if changes in other places are required as well.

**Comment by nilsleh** [comment]
At the top of my head the necessary changes (removing that argument) would be:
- the `deep_ensemble.py` file itself
- the config files of deep ensembles in `tests/configs`
- the tutorial notebooks  

But all of those will also be checked by unittests so we will see if there are other necessary changes.
