### ISSUE TITLE
One sigma confidence intervals in visualizations

### ISSUE THREAD

**Issue by elcorto** [lightning-uq-box/lightning-uq-box#155]
Visualizations of confidence bands (as shown in #147 for instance) uses $y\pm\sigma$ instead of the more common $y\pm 2\sigma$ for an approx. 95% confidence band width. This is also the default in `uncertainty_toolbox`. Is there a reason for this?

**Comment by nilsleh** [comment]
Thanks for the observation. I can't recall a specific reason, so I guess it was just imprecisely implemented from us. Suppose can also fix it in that PR and make the docstring more clear.

**Comment by nilsleh** [comment]
Fixed in #147.
