### ISSUE TITLE
Issue on page /tutorials/regression/conformal_qr.html

### ISSUE THREAD

**Issue by wccai** [lightning-uq-box/lightning-uq-box#184]
Hi,

I am looking at the tutorial, Conformalized Quantile Regression. I find the parameters of "ToyHeteroscedasticDatamodule" is updated. For example, " dm.X_gtext" is not valid.  The error message is  "AttributeError: 'ToyHeteroscedasticDatamodule' object has no attribute 'X_gtext'". Could you update the section "Datamodule"? 

Thank you.

**Comment by nilsleh** [comment]
Hi @wccai , thank you for your issue. I am afraid that I cannot reproduce the issue with the current main branch of the repository. For me it runs without errors, and also on the [documentation page](https://lightning-uq-box.readthedocs.io/en/latest/tutorials/regression/conformal_qr.html) where the notebooks are executed on the fly before becoming `.html` files, the conformal tutorial seems to run without errors. Could you provide more information about which version you are using? Thanks!

**Comment by wccai** [comment]
Hi @nilsleh,
For example, when I run it on the Colab. [link](https://colab.research.google.com/github/lightning-uq-box/lightning-uq-box/blob/main/docs/tutorials/regression/conformal_qr.ipynb) The following code needs to update.

```
dm = ToyHeteroscedasticDatamodule(n_points=1000, calib_fraction=0.6)

(
    X_train,
    Y_train,
    train_loader,
    X_test,
    Y_test,
    test_loader,
    X_calib,
    Y_calib,
    X_gtext,
    Y_gtext,
) = (
    dm.X_train,
    dm.Y_train,
    dm.train_dataloader(),
    dm.X_test,
    dm.Y_test,
    dm.test_dataloader(),
    dm.X_calib,
    dm.Y_calib,
    dm.X_gtext,
    dm.Y_gtext,
)

TypeError: ToyHeteroscedasticDatamodule.__init__() got an unexpected keyword argument 'n_points'
```

Also, when I try this, 

```
dm = ToyHeteroscedasticDatamodule(n_train=200, n_true=200, sigma=0.3)
(
    X_train,
    Y_train,
    train_loader,
    X_test,
    Y_test,
    test_loader,
    X_calib,
    Y_calib,
    X_gtext,
    Y_gtext,
) = (
    dm.X_train,
    dm.y_train,
    dm.train_dataloader(),
    dm.X_test,
    dm.y_test,
    dm.test_dataloader(),
    dm.X_calib,
    dm.y_calib,
    dm.X_gtext,
    dm.y_gtext,
)

AttributeError: 'ToyHeteroscedasticDatamodule' object has no attribute 'X_gtext'
```

Those are issues I met.

**Comment by nilsleh** [comment]
Hi @wccai , 

Thank you for the added details, You are indeed correct, thank you for spotting this inconsistency. The notebooks run okay during the tests, because they have the latest main version available when being pushed to the docs. However, if like in your case, you want to actually run the colab, the latest version from main also needs to be installed, not the stable version from pypi. So I believe the PR will fix the issue. Will wait for the tests to pass, check myself and let you know. Thanks again!
