### ISSUE TITLE
--use_ema_model not in CARDBase __init__ params

### ISSUE THREAD

**Issue by wrkhard** [lightning-uq-box/lightning-uq-box#239]
Resulting error arrises when trying to use ema with CARDRegressor:

  card_model = CARDRegression(
                 ^^^^^^^^^^^^^^^
TypeError: CARDBase.__init__() got an unexpected keyword argument 'use_ema_model'

**Comment by nilsleh** [comment]
Hi @wrkhard , sorry about the confusion, the `CARDRegressor` inherits from the base class `CARDBase` and I configured it such that ema weights are tracked by default, so one only has control over the ema parameters shown [here](https://github.com/lightning-uq-box/lightning-uq-box/blob/f3e817afac4891a73c84af18885ac0b1f3d997d0/lightning_uq_box/uq_methods/cards.py#L52) or seen in the [docs](https://lightning-uq-box.readthedocs.io/en/latest/api/uq_methods.html#card-base).

the `use_ema_model` is just a boolean flag that decides [here](https://github.com/lightning-uq-box/lightning-uq-box/blob/f3e817afac4891a73c84af18885ac0b1f3d997d0/lightning_uq_box/uq_methods/cards.py#L144) whether to use the model or the ema_model to do the forward pass. Let me know if this is more clear, and or suggestions how to make this more clear from the beginning.

**Comment by wrkhard** [comment]
Ahh, okay missed that. Thanks!
